### ISSUE TITLE
nginx-1.6.1-1.el6.ngx.x86_64.rpm is no longer available

### ISSUE THREAD

**Issue by Yuya-Kobayashi** [matsuu/ansible-isucon#11]
https://github.com/matsuu/ansible-isucon/blob/master/isucon4-qualifier/01_qualifier.yml
の中に書いてある
http://nginx.org/packages/old/centos/6/x86_64/nginx-1.6.1-1.el6.ngx.x86_64.rpm
が404: not foundを返します。

`==> default: TASK [yum] *********************************************************************
==> default: fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://nginx.org/packages/old/centos/6/x86_64/nginx-1.6.1-1.el6.ngx.x86_64.rpm, HTTP Error 404: Not Found"}
==> default: 	to retry, use: --limit @/home/vagrant/ansible-isucon/isucon4-qualifier/playbook.retry
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: localhost                  : ok=34   changed=2    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

**Comment by matsuu** [comment]
fixed. thanks
